version: '2.1'
services:

# ______________________________DUCKDNS_______________________________
  duckdns:
    image: linuxserver/duckdns
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Europe/Madrid
      - SUBDOMAINS=israelq,
      - TOKEN=6e57d7ab-c2e5-4181-989f-b7331f7d837b
      - LOG_FILE=false #optional
    volumes:
      - /home/israel/compose/data/duckdns/config:/config #optional
    restart: unless-stopped
# _____________________________SWAG______________________________________
  swag:
    image: linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - URL=israelq.duckdns.org
      - SUBDOMAINS=www,
      - VALIDATION=duckdns
      - DNSPLUGIN=cloudflare #optional
      - PROPAGATION= #optional
      - DUCKDNSTOKEN=6e57d7ab-c2e5-4181-989f-b7331f7d837b
      - EMAIL= #optional
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
    volumes:
      - /home/israel/compose/data/swag/config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped

#___________________________________PIHOLE_____________________________________
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 1080:80/tcp
      - 1443:443/tcp
    environment:
      TZ: Europe/Madrid
    volumes:
       - /home/israel/compose/data/pihole/etc-pihole/:/etc/pihole/
       - /home/israel/compose/data/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    dns:
      - 127.0.0.1
      - 1.1.1.1
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
# ____________________________ NEXTCLOUD __________________________________
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - /home/israel/compose/data/nextcloud/config:/config
      - /home/israel/compose/data/nextcloud/data:/data
    ports:
      - 2443:443
    restart: unless-stopped

# ________________________________QBITORRENT________________________________
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - UMASK_SET=022
      - WEBUI_PORT=8080
    volumes:
      - /home/pi/compose/data/qbittorrent/config:/config
      - /home/pi/compose/data/qbittorrent/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 3080:8080
    restart: unless-stopped
# ______________________________ JACKETT _________________________________
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - AUTO_UPDATE=true #optional
      - RUN_OPTS=<run options here> #optional
    volumes:
      - /home/israel/compose/data/jackett/config:/config
      - /home/israel/compose/data/jackett/downloads:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
# _____________________________ WIREWARD ______________________________
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SERVERURL=israelq.duckdns.org
      - SERVERPORT=51820 #optional
      - PEERS=2 #optional
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0 #optional
    volumes:
      - /home/israel/compose/data/wireguard/config:/config
      - /lib/modules:/lib/modules   # no modificar
    ports:
      - 51820:51820/udp     # Redireccionar puerto en router
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
# ____________________________ PLEX ____________________________________
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /home/israel/compose/plex/config:/config
      - /home/israel/series:/series
    restart: unless-stopped

# ______________________ PHP MY ADMIN________________________________
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Asir_2223

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

# _________________________ PORTAINER _______________________________

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainerWEB
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./portainer-data:/data
    ports:
      - 9000:9000
